In [1]:
import pdpipe
print(pdpipe.__version__)


0.2.8


In [2]:
from sys import path
path.append("/Users/shaypalachy/temp/")

import temp

In [2]:
import pdpipe
print(pdpipe.__version__)


0.2.8


In [1]:
# import tensorflow as tf

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 


Instructions for updating:
non-resource variables are not supported in the long term


In [6]:
sess = tf.InteractiveSession()
p = tf.placeholder(tf.float32, shape=[None, 5])
logit_q = tf.placeholder(tf.float32, shape=[None, 5])
q = tf.nn.sigmoid(logit_q)
sess.run(tf.global_variables_initializer())

/Users/shaypalachy/.pyenv/versions/3.10.2/envs/py3/lib/python3.10/site-packages/tensorflow/python/client/session.py:1768: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [10]:
feed_dict = {p: [[0, 0, 0, 1, 0], [1,0,0,0,0]], logit_q: [[0.2, 0.2, 0.2, 0.2, 0.2], [0.3, 0.3, 0.2, 0.1, 0.1]]}
loss1 = -tf.reduce_sum(p*tf.log(q),1).eval(feed_dict)
loss2 = tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(labels=p, logits=logit_q),1).eval(feed_dict)

print('p.eval(feed_dict):')
print(p.eval(feed_dict))
print('\n q.eval(feed_dict):')
print(q.eval(feed_dict))


print("\n loss1:",loss1, "\n loss2:", loss2)

p.eval(feed_dict):
[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]

 q.eval(feed_dict):
[[0.549834  0.549834  0.549834  0.549834  0.549834 ]
 [0.5744425 0.5744425 0.549834  0.5249792 0.5249792]]

 loss1: [0.5981388  0.55435526] 
 loss2: [3.7906942 3.6956425]


In [11]:
p = tf.placeholder(tf.float32, shape=[None, 2])
logit_q = tf.placeholder(tf.float32, shape=[None, 2])
q = tf.nn.softmax(logit_q)

feed_dict = {
  p: [[0, 1],
      [1, 0],
      [1, 0]],
  logit_q: [[0.2, 0.8],
            [0.7, 0.3],
            [0.5, 0.5]]
}

prob1 = -tf.reduce_sum(p * tf.log(q), axis=1)
prob2 = tf.nn.softmax_cross_entropy_with_logits(labels=p, logits=logit_q)
print(prob1.eval(feed_dict))  # [ 0.43748799  0.51301527  0.69314718]
print(prob2.eval(feed_dict))  # [ 0.43748799  0.51301527  0.69314718]

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

[0.437488  0.5130153 0.6931472]
[0.437488  0.5130153 0.6931472]


In [13]:
p = tf.placeholder(tf.float32, shape=[None, 5])
logit_q = tf.placeholder(tf.float32, shape=[None, 5])
q = tf.nn.sigmoid(logit_q)

feed_dict = {
  p: [[0, 0, 0, 1, 0],
      [1, 0, 0, 0, 0]],
  logit_q: [[0.2, 0.2, 0.2, 0.2, 0.2],
            [0.3, 0.3, 0.2, 0.1, 0.1]]
}

prob1 = -p * tf.log(q)
prob2 = p * -tf.log(q) + (1 - p) * -tf.log(1 - q)
prob3 = p * -tf.log(tf.sigmoid(logit_q)) + (1-p) * -tf.log(1-tf.sigmoid(logit_q))
prob4 = tf.nn.sigmoid_cross_entropy_with_logits(labels=p, logits=logit_q)
print('prob1:')
print(prob1.eval(feed_dict))
print('prob2:')
print(prob2.eval(feed_dict))
print('prob3:')
print(prob3.eval(feed_dict))
print('prob4 [sigmoid_cross_entropy_with_logits]:')
print(prob4.eval(feed_dict))

prob1:
[[0.         0.         0.         0.5981388  0.        ]
 [0.55435526 0.         0.         0.         0.        ]]
prob2:
[[0.7981389  0.7981389  0.7981389  0.5981388  0.7981389 ]
 [0.55435526 0.8543552  0.7981389  0.7443966  0.7443966 ]]
prob3:
[[0.7981389  0.7981389  0.7981389  0.5981388  0.7981389 ]
 [0.55435526 0.8543552  0.7981389  0.7443966  0.7443966 ]]
prob4 [sigmoid_cross_entropy_with_logits]:
[[0.79813886 0.79813886 0.79813886 0.59813887 0.79813886]
 [0.5543552  0.8543552  0.79813886 0.7443967  0.7443967 ]]
